name: Publish Package to NPM and GitHub Packages

on:
  release:
    types: [created] # Triggers when a new GitHub Release is published
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for GitHub Packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # At this point, package.json in the workspace has name: "docmd"

      - name: Set up Node.js (common for initial steps)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # --- Publish to NPM Registry (npmjs.com) ---
      - name: Set up Node.js for npmjs.com
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/' # Point to public NPM registry

      # This step ensures the name is "docmd" and removes any publishConfig.
      # If your repo's package.json is already "docmd" and has no publishConfig,
      # this step mainly acts as a safeguard and version re-assertion.
      - name: Ensure package.json is set for npmjs.com (publish as docmd)
        run: |
          echo "Current package.json before npmjs.com publish:"
          cat package.json
          VERSION=$(node -p "require('./package.json').version")
          # Ensure name is "docmd" and remove publishConfig if it exists
          jq --arg newName "docmd" --arg newVersion "$VERSION" '.name = $newName | .version = $newVersion | del(.publishConfig)' package.json > package_temp.json
          mv package_temp.json package.json
          echo "package.json for npmjs.com publishing:"
          cat package.json

      - name: Publish to NPM Registry (npmjs.com)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # --- Publish to GitHub Packages ---
      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com' # Point to GitHub Packages registry
          scope: '@mgks' # Crucial: Configures .npmrc for this scope

      # At this point, package.json name is "docmd".
      # This step changes it to "@mgks/docmd" for GPR.
      - name: Adjust package.json for GitHub Packages (publish as @mgks/docmd)
        run: |
          echo "Current package.json before GPR publish (should be 'docmd'):"
          cat package.json
          VERSION=$(node -p "require('./package.json').version")
          # Change name to "@mgks/docmd"
          jq --arg newName "@mgks/docmd" --arg newVersion "$VERSION" '.name = $newName | .version = $newVersion' package.json > package_temp.json
          mv package_temp.json package.json
          echo "Updated package.json for GPR publishing:"
          cat package.json

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}